apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: default
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: localhost:32000/elasticsearch:7.14.2
        name: elasticsearch
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: elastic-volume
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elastic-volume
        persistentVolumeClaim:
          claimName: elastic-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch-9200
  name: elasticsearch-9200
  namespace: default
spec:
  ports:
  - port: 9200
    protocol: TCP
    name: "9200"
    nodePort: 30200
    targetPort: 9200
  selector:
    app: elasticsearch
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch-9300
  name: elasticsearch-9300
  namespace: default
spec:
  ports:
  - port: 9300
    protocol: TCP
    nodePort: 30300
    name: "9300"
    targetPort: 9300
  selector:
    app: elasticsearch
  type: NodePort
  #####################################
---
