apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: wurstmeister/kafka
        name: kafka
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: localhost
        - name: KAFKA_CREATE_TOPICS
          value: "rss_data:1:1,crawled_news:1:1,logs:1:1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.0.0.1:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://10.0.0.1:9092
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-cluster
spec:
  externalIPs:
  - 10.0.0.1
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
status:
  loadBalancer: {}
