apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rssparser
  name: rssparser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rssparser
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rssparser
    spec:
      containers:
      - image: localhost:32000/rssparser2
        name: rssparser
        resources: {}
status: {}
