apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rssparser
  name: rssparser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rssparser
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rssparser
    spec:
      containers:
      - image: localhost:32000/rssparser
        name: rssparser
        resources: {}
        volumeMounts:
        - name: rssparser-volume
          mountPath: /usr/src/myapp/Logs/
      volumes:
      - name: rssparser-volume
        persistentVolumeClaim:
          claimName: rssparser-volume
status: {}

