kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mysql
  name: mysql-volume
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi